### ISSUE TITLE
isn't runHalogenAff equal to launchAff_ ? maybe explicitly alias it?

### ISSUE THREAD

**Issue by srghma** [purescript-halogen/purescript-halogen#666]
Isn't it results in the same behavior?

```
-- | Runs an `Aff` value of the type commonly used by Halogen components. Any
-- | unhandled errors will be re-thrown as exceptions.
runHalogenAff :: forall x. Aff x -> Effect Unit
runHalogenAff = runAff_ (either throwException (const (pure unit)))
```

```
-- | Forks an `Aff` from an `Effect` context, discarding the `Fiber`.
launchAff_ ∷ ∀ a. Aff a → Effect Unit
launchAff_ = void <<< launchAff

-- | Forks an `Aff` from an `Effect` context and also takes a callback to run when
-- | it completes. Returns the pending `Fiber`.
runAff ∷ ∀ a. (Either Error a → Effect Unit) → Aff a → Effect (Fiber Unit)
runAff k aff = launchAff $ liftEffect <<< k =<< try aff

-- | Forks an `Aff` from an `Effect` context and also takes a callback to run when
-- | it completes, discarding the `Fiber`.
runAff_ ∷ ∀ a. (Either Error a → Effect Unit) → Aff a → Effect Unit
runAff_ k aff = void $ runAff k aff
```

**Comment by garyb** [comment]
`launchAff_` discard errors that arise entirely, if I remember rightly. Also at the time it was added I don't think there was a `launchAff_`.

**Comment by srghma** [comment]
no, it doesn't discard errors, I have checked :)


```
main = launchAff_ do
  void $ throwError $ Exception.error "asdf"
```


```
Error: asdf
    at Object../output/Effect.Exception/foreign.js.exports.error (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:61087:10)
    at Object../app/Server.purs (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:248:225)
    at __webpack_require__ (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:20:30)
    at Object../app/server.entry.js (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:298:1)
    at __webpack_require__ (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:20:30)
    at /home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:84:18
    at Object.<anonymous> (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
```

**Comment by srghma** [comment]
The result is the same as with 

```
main = runHalogenAff do
  void $ throwError $ Exception.error "asdf"
```

```

Error: asdf
    at Object../output/Effect.Exception/foreign.js.exports.error (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:61088:10)
    at Object../app/Server.purs (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:249:234)
    at __webpack_require__ (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:20:30)
    at Object../app/server.entry.js (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:299:1)
    at __webpack_require__ (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:20:30)
    at /home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:84:18
    at Object.<anonymous> (/home/srghma/projects/purescript-halogen-nextjs/.dist-dev/server/server.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
```
